# Generated by Django 3.2.18 on 2023-09-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20230914_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
