# Generated by Django 3.2.18 on 2023-09-15 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2015, 10, 9, 23, 55, 59, 342380)),
        ),
    ]
