# Generated by Django 3.2.18 on 2023-09-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='date',
        ),
    ]
